version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: $1q2w3e4r
    volumes:
      - ./vol-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
